import { SellableInventory } from "@/@types/SellableInventoy";
export type ItemVariant = {
    id: number;
    uid: string;
    pindex: number;
    pattern_4points: string;
    pattern_6points: string;
    metadata: Record<string, unknown>;
    platform_item_variant_id: string;
    qr_barcode: string;
    hash_code: string;
    barcode_type: string;
    barcode: string;
    asin: string;
    description: string;
    packing_width: number;
    packing_height: number;
    packing_length: number;
    packing_weight: number;
    gross_weight: number;
    net_weight: number;
    gross_volume: number;
    net_volume: number;
    price_updated_at: string;
    created_at: string;
    updated_at: string;
    item_id: number;
    company_id: number;
    integration_account_id: number;
    item_packing_style_id: number;
    item_platform_id: number;
    item_sku_id: number;
    item_lot_id: number;
    length_unit_code: string;
    weight_unit_code: string;
    volume_unit_code: string;
    sellable_inventory_id: number;
    item_lot_is_null: boolean;
    sellable_inventory: SellableInventory;
};
