export type ShopeeItem = {
    id: number;
    shopee_item_id: string;
    category_id: string;
    item_name: string;
    description: string;
    item_sku_code: string;
    attribute_value_list: Record<string, unknown>;
    price_info: Record<string, unknown>;
    image: Record<string, unknown>;
    weight: string;
    dimension: Record<string, unknown>;
    logistic_info: Record<string, unknown>;
    pre_order: Record<string, unknown>;
    wholesales: Record<string, unknown>;
    condition: string;
    size_chart: string;
    item_status: string;
    deboost: boolean;
    has_model: boolean;
    has_promotion: boolean;
    video_info: Record<string, unknown>;
    brand: Record<string, unknown>;
    item_dangerous: number;
    gtin_code: string;
    size_chart_id: number;
    promotion_image: Record<string, unknown>;
    compatibility_info: Record<string, unknown>;
    scheduled_publish_time: string;
    is_fulfillment_by_shopee: boolean;
    is_kit: boolean;
    purchase_limit: Record<string, unknown>;
    medicine_id: number;
    certification_info: Record<string, unknown>;
    complaint_policy: Record<string, unknown>;
    tax_info: Record<string, unknown>;
    description_info: Record<string, unknown>;
    description_type: string;
    stock_info_v2: Record<string, unknown>;
    authorised_brand_id: number;
    sale: number;
    views: number;
    likes: number;
    rating_star: number;
    comment_count: number;
    item_platform_id: number;
    integration_account_id: number;
};
